### ISSUE TITLE
Error flow in provision workflow.

### ISSUE THREAD

**Issue by jaredm-ibm** [ManageIQ/manageiq-providers-ibm_cloud#201]
Issue to track the error flow scenarios and their solutions.

## Exception preventing initial dialog load. ##
 - [x] UI should print a standard message in a pop-up window with directions to cancel.
 - [x] Exception should be printed to provider log.

## Exception while fetching data for dialog ##
 - [x] Dialog box should hold 1 value with message indicating error.
 - [x] Exception should be printed to provider log.

## Exception while processing data for dialog ##
 - [x] Dialog box should hold 1 value with message indicating error.
 - [x] Exception should be printed to provider log.
 - [x] Exact nature of error should be evident.

## Exception during standard field validation
 - [x] Exception should be printed to provider log.
 - [x] default_ui_error_msg error is printed to UI

## Exception during new volume field creation
 - [x] Exception should be printed to provider log.
 - [x] default_ui_error_msg error is printed to UI

## Exception during new volume validation
- [x] Unhandled exceptions should be printed to provider log.
- [x] Validation Exceptions are not printed anywhere.
- [x] Unhandled exceptions print default UI message.
- [x] Validation Exceptions print specific message.

**Comment by jaredm-ibm** [comment]
# Test scenario 1: Exception preventing initial dialog load.
Simulate an unhandled exception in a method not called by field population methods.
The flow is something like: UI -> Workflow -> Field -> ActiveRecord -> ar_ems

* In `ar_ems` change `rui = resources_for_ui[:ems]` to `rui = break_resources_for_ui[:ems]`. This will raise an unexpected NameError.
* ar_ems has a exception rescue backtrace block.

In UI start provision:
1. Choose image and click 'Continue'.
2. Error message is presented with.
<img width="741" alt="Screen Shot 2021-05-05 at 12 29 13 PM" src="https://user-images.githubusercontent.com/60901094/117188890-8eb26180-adab-11eb-8698-7d16680a5573.png">

3. Click cancel button.
<img width="655" alt="Screen Shot 2021-05-05 at 12 29 33 PM" src="https://user-images.githubusercontent.com/60901094/117188953-9a9e2380-adab-11eb-82e7-79614b971915.png">

4. Click Instances by Provider link
<img width="514" alt="Screen Shot 2021-05-05 at 12 29 55 PM" src="https://user-images.githubusercontent.com/60901094/117188969-a12c9b00-adab-11eb-8dc0-ddb971a42412.png">
5. Click menu item
<img width="696" alt="Screen Shot 2021-05-05 at 12 30 07 PM" src="https://user-images.githubusercontent.com/60901094/117188979-a558b880-adab-11eb-9dfe-bfad8abf6c83.png">

## provider log
[----] E, [2021-05-05T14:02:37.729454 #35638:3fcf2c9e1b9c] ERROR -- : ManageIQ::Providers::IbmCloud::VPC::CloudManager::ProvisionWorkflow.ar_ems Fetching ems for VPC cloud.
[----] E, [2021-05-05T14:02:37.795267 #35638:3fcf2c9e1b9c] ERROR -- : [NameError]: undefined local variable or method `break_resources_for_ui' for #<ManageIQ::Providers::IbmCloud::VPC::CloudManager::ProvisionWorkflow:0x00007f9e4adfc4c0>  Method:[rescue in ar_ems]
[----] E, [2021-05-05T14:02:37.795605 #35638:3fcf2c9e1b9c] ERROR -- : ./manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/common.rb:11:in `ar_ems'
./manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/general.rb:9:in `provision_type_to_profile'
./manageiq/app/models/miq_request_workflow.rb:288:in `get_field'
./manageiq/app/models/miq_request_workflow.rb:275:in `block in get_all_fields'
./manageiq/app/models/miq_request_workflow.rb:275:in `each_key'
./manageiq/app/models/miq_request_workflow.rb:275:in `get_all_fields'
./manageiq/app/models/miq_request_workflow.rb:267:in `get_dialog'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:892:in `block in prov_set_form_vars'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:891:in `each'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:891:in `prov_set_form_vars'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:248:in `prov_edit'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:111:in `pre_prov'
... truncate
./manageiq/graphql/rest_api_proxy.rb:18:in `call'
./manageiq/lib/request_started_on_middleware.rb:12:in `call'
... truncate
[----] E, [2021-05-05T14:02:37.795756 #35638:3fcf2c9e1b9c] ERROR -- : ManageIQ::Providers::IbmCloud::VPC::CloudManager::ProvisionWorkflow.provision_type_to_profile printing raised exception
[----] E, [2021-05-05T14:02:37.796878 #35638:3fcf2c9e1b9c] ERROR -- : [NameError]: undefined local variable or method `break_resources_for_ui' for #<ManageIQ::Providers::IbmCloud::VPC::CloudManager::ProvisionWorkflow:0x00007f9e4adfc4c0>  Method:[ui_exception]
[----] E, [2021-05-05T14:02:37.796978 #35638:3fcf2c9e1b9c] ERROR -- : ./manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/common.rb:11:in `ar_ems'
./manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/general.rb:9:in `provision_type_to_profile'
./manageiq/app/models/miq_request_workflow.rb:288:in `get_field'
./manageiq/app/models/miq_request_workflow.rb:275:in `block in get_all_fields'
./manageiq/app/models/miq_request_workflow.rb:275:in `each_key'
./manageiq/app/models/miq_request_workflow.rb:275:in `get_all_fields'
./manageiq/app/models/miq_request_workflow.rb:267:in `get_dialog'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:892:in `block in prov_set_form_vars'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:891:in `each'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:891:in `prov_set_form_vars'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:248:in `prov_edit'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:111:in `pre_prov'
... truncate
./manageiq/graphql/rest_api_proxy.rb:18:in `call'
./manageiq/lib/request_started_on_middleware.rb:12:in `call'
... truncate
## develoment log
[----] D, [2021-05-05T13:33:12.167489 #33086:3fd5eaeb25e4] DEBUG -- :   ExtManagementSystem Load (1.0ms)  SELECT "ext_management_systems".* FROM "ext_management_systems" WHERE "ext_management_systems"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
[----] D, [2021-05-05T13:33:12.169201 #33086:3fd5eaeb25e4] DEBUG -- :   ExtManagementSystem Inst Including Associations (0.8ms - 1rows)
[----] F, [2021-05-05T13:33:12.303357 #33086:3fd5eaeb25e4] FATAL -- : Error caught: [MiqException::MiqProvisionError] A server-side error occurred in the provisioning workflow, contact your administrator. Use the menu or "instances by Provider" link to cancel this workflow.
./manageiq/providers/ibm_cloud/vpc/cloud_manager/logging_mixin.rb:72:in `ui_exception'
./manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/general.rb:12:in `rescue in provision_type_to_profile'
./manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/general.rb:8:in `provision_type_to_profile'
./manageiq/app/models/miq_request_workflow.rb:288:in `get_field'
./manageiq/app/models/miq_request_workflow.rb:275:in `block in get_all_fields'
./manageiq/app/models/miq_request_workflow.rb:275:in `each_key'
./manageiq/app/models/miq_request_workflow.rb:275:in `get_all_fields'
./manageiq/app/models/miq_request_workflow.rb:267:in `get_dialog'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:892:in `block in prov_set_form_vars'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:891:in `each'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:891:in `prov_set_form_vars'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:248:in `prov_edit'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:111:in `pre_prov'
... truncate
./manageiq/lib/request_started_on_middleware.rb:12:in `call'
... truncate

## evm log
[----] I, [2021-05-05T14:02:37.474203 #35638:3fcf2c9e1b9c]  INFO -- : MIQ(ManageIQ::Providers::IbmCloud::VPC::CloudManager::ProvisionWorkflow#get_dialogs) Loading dialogs <miq_provision_vpc_dialogs> for user <admin>
[----] I, [2021-05-05T14:02:46.237515 #35637:3fcedb432044]  INFO -- : MIQ(MiqScheduleWorker::Runner#do_work) Number of scheduled items to be processed: 2.

**Comment by jaredm-ibm** [comment]
# Scenario 2 Issue with data in proovision
Simulate the wrong object being passed in.
in `provision_type_to_profile` replace ar_ems.flavors with an array. The expected data type is a hash-like object.

1. Select image and press continue.
2. System profiles has default short message.

<img width="402" alt="Screen Shot 2021-05-05 at 4 25 14 PM" src="https://user-images.githubusercontent.com/60901094/117204820-d42c5a00-adbe-11eb-879b-c0294ec49773.png">

3. Rest of system is still responsive.

<img width="433" alt="Screen Shot 2021-05-05 at 4 25 57 PM" src="https://user-images.githubusercontent.com/60901094/117204875-e4443980-adbe-11eb-926a-833940eb21b2.png">


4. Cancel button works.

<img width="902" alt="Screen Shot 2021-05-05 at 4 26 24 PM" src="https://user-images.githubusercontent.com/60901094/117204919-ee663800-adbe-11eb-85aa-e41541663991.png">


## provider log ##

```
[----] E, [2021-05-05T16:18:49.301579 #50448:3fc4f2146f94] ERROR -- : ManageIQ::Providers::IbmCloud::VPC::CloudManager::ProvisionWorkflow.index_dropdown `provision_type_to_profile' exception with Array using id => name
[----] E, [2021-05-05T16:18:49.301839 #50448:3fc4f2146f94] ERROR -- : [RuntimeError]: Integer does not have respond to name.  Method:[rescue in index_dropdown]
[----] E, [2021-05-05T16:18:49.302106 #50448:3fc4f2146f94] ERROR -- : ./manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/fields.rb:86:in `find_key'
./manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/fields.rb:65:in `block in generic_dropdown'
./manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/fields.rb:64:in `each'
./manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/fields.rb:64:in `each_with_object'
./manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/fields.rb:64:in `generic_dropdown'
./manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/fields.rb:47:in `index_dropdown'
./manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/general.rb:11:in `provision_type_to_profile'
./manageiq/app/models/miq_request_workflow.rb:288:in `get_field'
./manageiq/app/models/miq_request_workflow.rb:275:in `block in get_all_fields'
./manageiq/app/models/miq_request_workflow.rb:275:in `each_key'
./manageiq/app/models/miq_request_workflow.rb:275:in `get_all_fields'
./manageiq/app/models/miq_request_workflow.rb:267:in `get_dialog'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:892:in `block in prov_set_form_vars'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:891:in `each'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:891:in `prov_set_form_vars'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:248:in `prov_edit'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:111:in `pre_prov'
... truncate non-miq
./manageiq/graphql/rest_api_proxy.rb:18:in `call'
./manageiq/lib/request_started_on_middleware.rb:12:in `call'
... truncate non-miq
```

## Reading from log/development.log ==

```
[----] I, [2021-05-05T16:18:49.111450 #50448:3fc4f2146f94]  INFO -- : Started POST "/vm_cloud/pre_prov?button=continue" for 127.0.0.1 at 2021-05-05 16:18:49 -0400
[----] I, [2021-05-05T16:18:49.267327 #50448:3fc4f2146f94]  INFO -- : Processing by VmCloudController#pre_prov as JS
[----] I, [2021-05-05T16:18:49.267446 #50448:3fc4f2146f94]  INFO -- :   Parameters: {"button"=>"continue"}
[----] D, [2021-05-05T16:18:49.269491 #50448:3fc4f2146f94] DEBUG -- : PostgreSQLAdapter#log_after_checkout, connection_pool: size: 8, connections: 4, in use: 2, waiting_in_queue: 0
[----] D, [2021-05-05T16:18:49.270403 #50448:3fc4f2146f94] DEBUG -- :   User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" BETWEEN $1 AND $2 AND "users"."userid" = $3 LIMIT $4  [["id", 0], ["id", 999999999999], ["userid", "admin"], ["LIMIT", 1]]
[----] D, [2021-05-05T16:18:49.271004 #50448:3fc4f2146f94] DEBUG -- :   User Inst Including Associations (0.2ms - 1rows)
```

## Reading from log/evm.log ##

```
[----] I, [2021-05-05T16:18:49.286372 #50448:3fc4f2146f94]  INFO -- : MIQ(ManageIQ::Providers::IbmCloud::VPC::CloudManager::ProvisionWorkflow#get_dialogs) Loading dialogs <miq_provision_vpc_dialogs> for user <admin>
[----] I, [2021-05-05T16:18:49.356066 #50448:3fc4f2146f94]  INFO -- : MIQ(ManageIQ::Providers::IbmCloud::VPC::CloudManager::ProvisionWorkflow#refresh_field_values) provision refresh completed in [0.023014] seconds
[----] I, [2021-05-05T16:18:49.361570 #50448:3fc4f2146f94]  INFO -- : MIQ(ManageIQ::Providers::IbmCloud::VPC::CloudManager::ProvisionWorkflow#get_ems_metadata_tree) EMS metadata collection completed in [0.00532] seconds
[----] W, [2021-05-05T16:18:49.401792 #50448:3fc4f2146f94]  WARN -- : MIQ(ManageIQ::Providers::IbmCloud::VPC::CloudManager::ProvisionWorkflow#log_allowed_template_list) Allowed Templates is returning <111> template(s)
```

**Comment by jaredm-ibm** [comment]
# Scenario 2a Issue with data in workflow and user clicks Submit

Simulate the wrong object being passed in.
in `provision_type_to_profile` replace ar_ems.flavors with an array. The expected data type is a hash-like object.

1. Select image and press continue.
2. System profiles has default short message.
3. Fill out default values.
4. Click Continue

<img width="964" alt="Screen Shot 2021-05-05 at 4 32 14 PM" src="https://user-images.githubusercontent.com/60901094/117205822-1e620b00-adc0-11eb-998c-8ffa78c9af54.png">


No logs to capture

**Comment by jaredm-ibm** [comment]
Updated the exception message to be.
```
'A server-side error prevents this form from being submitted. Contact your administrator. To leave this form use the Cancel button.'
```

**Comment by jaredm-ibm** [comment]
# Scenario 3 Exception while trying to proccess data.
In `provision_type_to_profile` change the value to look for the field `'no_exist'` instead of `:name`

1. Get to dialog form.
2. Form should have 1 value with error message.


## Reading from log/ibm_cloud.log ##
```
[----] E, [2021-05-05T17:54:01.277491 #64214:3fc6ccafe344] ERROR -- : ManageIQ::Providers::IbmCloud::VPC::CloudManager::ProvisionWorkflow.index_dropdown `provision_type_to_profile' exception with ActiveRecord::Associations::CollectionProxy using id => no_exist
[----] E, [2021-05-05T17:54:01.278398 #64214:3fc6ccafe344] ERROR -- : [RuntimeError]: Flavor does not respond to 'no_exist'.  Method:[rescue in index_dropdown]
[----] E, [2021-05-05T17:54:01.278688 #64214:3fc6ccafe344] ERROR -- : ./manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/fields.rb:86:in `find_key'
./manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/fields.rb:65:in `block in generic_dropdown'
/Users/jaredmca.ibm.com/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/relation/delegation.rb:87:in `each'
/Users/jaredmca.ibm.com/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/relation/delegation.rb:87:in `each'
./manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/fields.rb:64:in `each_with_object'
./manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/fields.rb:64:in `generic_dropdown'
./manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/fields.rb:47:in `index_dropdown'
./manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/general.rb:9:in `provision_type_to_profile'
./manageiq/app/models/miq_request_workflow.rb:288:in `get_field'
./manageiq/app/models/miq_request_workflow.rb:275:in `block in get_all_fields'
./manageiq/app/models/miq_request_workflow.rb:275:in `each_key'
./manageiq/app/models/miq_request_workflow.rb:275:in `get_all_fields'
./manageiq/app/models/miq_request_workflow.rb:267:in `get_dialog'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:892:in `block in prov_set_form_vars'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:891:in `each'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:891:in `prov_set_form_vars'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:248:in `prov_edit'
./manageiq-ui-classic-634700500a5a/app/controllers/application_controller/miq_request_methods.rb:111:in `pre_prov'
```

**Comment by jaredm-ibm** [comment]
## Scenario 5: Exception during new volume field creation

In `create_new_volumes_array` add blind strip to form values.

UI error: A server-side error occurred in the provisioning workflow, contact your administrator. Use the menu or "instances by Provider" link to cancel this workflow.

```
[----] E, [2021-05-06T16:08:56.340339 #95437:3ff655d80f64] ERROR -- : ManageIQ::Providers::IbmCloud::VPC::CloudManager::ProvisionWorkflow.create_new_volumes_array Creating new_volume array.
[----] E, [2021-05-06T16:08:56.349843 #95437:3ff655d80f64] ERROR -- : [NoMethodError]: undefined method `strip' for [69, "ibm-debian-10-8-minimal-amd64-1"]:Array  Method:[ui_exception]
[----] E, [2021-05-06T16:08:56.350152 #95437:3ff655d80f64] ERROR -- : ./manageiq-providers-ibm_cloud/app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/volumes.rb:52:in `block in create_new_volumes_array'
```

**Comment by jaredm-ibm** [comment]
## Scenario 4: Exception during standard field validation
In validate_vm_name force value to be an integer.

UI Message -> Standard error.

Provider log
```
[----] E, [2021-05-06T16:42:28.158725 #98533:3fe705992bdc] ERROR -- : ManageIQ::Providers::IbmCloud::VPC::CloudManager::ProvisionWorkflow.validate_vm_name printing raised exception
[----] E, [2021-05-06T16:42:28.166080 #98533:3fe705992bdc] ERROR -- : [NoMethodError]: undefined method `length' for 0:Integer  Method:[ui_exception]
[----] E, [2021-05-06T16:42:28.166414 #98533:3fe705992bdc] ERROR -- : ./manageiq-providers-ibm_cloud/app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/general.rb:22:in `validate_vm_name'
```

**Comment by jaredm-ibm** [comment]
# Test 5: Exception during new volume validation

## Test 1: Unhandled exception
In validate_volume_required change logger call from debug to debugs

Default UI Error message is printed.

### Provider log

```
[----] E, [2021-05-07T08:37:09.091121 #18924:3feb3bfe3060] ERROR -- : ManageIQ::Providers::IbmCloud::VPC::CloudManager::ProvisionWorkflow.set_request_values printing raised exception
[----] E, [2021-05-07T08:37:09.097895 #18924:3feb3bfe3060] ERROR -- : [NoMethodError]: undefined method `debugs' for #<ManageIQ::Providers::IbmCloud::VPC::CloudManager::LoggingMixin::LoggingWrapper:0x00007fd67d0b7290>
Did you mean?  debug  Method:[ui_exception]
[----] E, [2021-05-07T08:37:09.098312 #18924:3feb3bfe3060] ERROR -- : ./manageiq-providers-ibm_cloud/app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/volumes.rb:97:in `validate_volume_required'
```

## Test 2: Validation failed
In UI provide invalid values in New Volumes field.

* Name: ddd$$$
* Volume Profile: nil
* Size: nil

Validation exception message is thrown.
No logs in provider.

## Test 3: All validations passed.
All fields are properly filled out.
Provision is submitted.
