### ISSUE TITLE
IBM VPC Add method check to cloud tool.

### ISSUE THREAD

**Issue by jaredm-ibm** [ManageIQ/manageiq-providers-ibm_cloud#206]
The cloud tool methods request and collection take a method argument. This should be checked to ensure that the method exists before using it. If it doesn't a suitable error message is provided.

**Comment by jaredm-ibm** [comment]
# Test 1: collection only accepts list method.

Pass in something that is supposed to fail.

`:get_instance` exists

```
[1] pry(main)> _vpc.request(:get_instance)
ArgumentError: missing keyword: id
from /Users/jaredmca.ibm.com/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/ibm_vpc-0.1.0/lib/ibm_vpc/vpc_v1.rb:2960:in `get_instance'
```

Runtime Error raised with method that starts with 'get'.

```
[2] pry(main)> _vpc.collection(:get_instance)
RuntimeError: Provided call_back get_instance does not start with list. This method is for paginating list methods.
from /Users/jaredmca.ibm.com/Documents/Code/miq/manageiq-providers-ibm_cloud/lib/manageiq/providers/ibm_cloud/cloud_tools/sdk/branch.rb:40:in `collection'
```

Collection allows list method

```
[3] pry(main)> _vpc.collection(:list_instances)
=> #<Enumerator: ...>
```

**Comment by jaredm-ibm** [comment]
# Test 2: Methods that don't exist raise error.

Collection

```
[8] pry(main)> _vpc.collection(:list_instancess).to_a
RuntimeError: IbmVpc::VpcV1 does not contain a method list_instancess
from /Users/jaredmca.ibm.com/Documents/Code/miq/manageiq-providers-ibm_cloud/lib/manageiq/providers/ibm_cloud/cloud_tools/sdk/branch.rb:74:in `send_request'
```

request

```
[10] pry(main)> _vpc.request(:list_instancess).to_a
RuntimeError: IbmVpc::VpcV1 does not contain a method list_instancess
from /Users/jaredmca.ibm.com/Documents/Code/miq/manageiq-providers-ibm_cloud/lib/manageiq/providers/ibm_cloud/cloud_tools/sdk/branch.rb:74:in `send_request'
```
