### ISSUE TITLE
VPC refresh fails due to timeouts on volumes API calls

### ISSUE THREAD

**Issue by nasark** [ManageIQ/manageiq-providers-ibm_cloud#294]
Since this appears to be an issue on the IBM Cloud side, the following workarounds were attempted:
- Increase timeouts: The timeout is thrown at the API level in the form of `[IBMCloudSdkCore::ApiException]: Error: Internal Server Error`
- Request retries

IBM Cloud UI:
<img width="897" alt="Screen Shot 2021-10-12 at 12 10 59 PM" src="https://user-images.githubusercontent.com/48186199/137018749-a6c8ba04-3911-4f12-9346-a9986d3f3cb6.png">

```
{
  "name": "RequestError",
  "error": {
    "code": "ESOCKETTIMEDOUT",
    "connect": false
  },
  "options": {
    "method": "GET",
    "headers": {
      "X-Request-ID": "8eecadb2-4936-4a23-97f3-76db6254f56b"
    },
    "url": "https://us-south.iaas.cloud.ibm.com/v1/volumes?version=2021-09-28&generation=2&limit=10&sort=name"
  }
}
```

Stack trace:
```
[----] E, [2021-10-12T12:00:22.730857 #68574:9434] ERROR -- evm: MIQ(ManageIQ::Providers::IbmCloud::VPC::CloudManager::Refresher#refresh) EMS: [nasar], id: [5] Refresh failed
[----] E, [2021-10-12T12:00:22.731170 #68574:9434] ERROR -- evm: [HTTP::TimeoutError]: Timed out after using the allocated 60 seconds  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2021-10-12T12:00:22.731260 #68574:9434] ERROR -- evm: /Users/nasarkhan/.rvm/gems/ruby-2.7.3/gems/http-4.4.1/lib/http/timeout/global.rb:125:in `log_time'
/Users/nasarkhan/.rvm/gems/ruby-2.7.3/gems/http-4.4.1/lib/http/timeout/global.rb:107:in `wait_readable_or_timeout'
/Users/nasarkhan/.rvm/gems/ruby-2.7.3/gems/http-4.4.1/lib/http/timeout/global.rb:89:in `block in perform_io'
/Users/nasarkhan/.rvm/gems/ruby-2.7.3/gems/http-4.4.1/lib/http/timeout/global.rb:84:in `loop'
/Users/nasarkhan/.rvm/gems/ruby-2.7.3/gems/http-4.4.1/lib/http/timeout/global.rb:84:in `perform_io'
/Users/nasarkhan/.rvm/gems/ruby-2.7.3/gems/http-4.4.1/lib/http/timeout/global.rb:50:in `readpartial'
/Users/nasarkhan/.rvm/gems/ruby-2.7.3/gems/http-4.4.1/lib/http/connection.rb:212:in `read_more'
/Users/nasarkhan/.rvm/gems/ruby-2.7.3/gems/http-4.4.1/lib/http/connection.rb:103:in `read_headers!'
/Users/nasarkhan/.rvm/gems/ruby-2.7.3/gems/http-4.4.1/lib/http/client.rb:75:in `perform'
/Users/nasarkhan/.rvm/gems/ruby-2.7.3/gems/http-4.4.1/lib/http/client.rb:31:in `request'
/Users/nasarkhan/.rvm/gems/ruby-2.7.3/gems/ibm_cloud_sdk_core-1.1.3/lib/ibm_cloud_sdk_core/base_service.rb:103:in `request'
/Users/nasarkhan/Documents/vpc-ruby-sdk/lib/ibm_vpc/vpc_v1.rb:5289:in `get_volume'
/Users/nasarkhan/Documents/manageiq/plugins/manageiq-providers-ibm_cloud/lib/manageiq/providers/ibm_cloud/cloud_tools/sdk/branch.rb:80:in `send_request'
/Users/nasarkhan/Documents/manageiq/plugins/manageiq-providers-ibm_cloud/lib/manageiq/providers/ibm_cloud/cloud_tools/sdk/branch.rb:51:in `request'
/Users/nasarkhan/Documents/manageiq/plugins/manageiq-providers-ibm_cloud/app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc.rb:96:in `volume'
/Users/nasarkhan/Documents/manageiq/plugins/manageiq-providers-ibm_cloud/app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb:109:in `block in instance_storage'
/Users/nasarkhan/Documents/manageiq/plugins/manageiq-providers-ibm_cloud/app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb:108:in `each'
/Users/nasarkhan/Documents/manageiq/plugins/manageiq-providers-ibm_cloud/app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb:108:in `instance_storage'
/Users/nasarkhan/Documents/manageiq/plugins/manageiq-providers-ibm_cloud/app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb:104:in `instance_hardware'
/Users/nasarkhan/Documents/manageiq/plugins/manageiq-providers-ibm_cloud/app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb:61:in `block in instances'
/Users/nasarkhan/Documents/manageiq/plugins/manageiq-providers-ibm_cloud/lib/manageiq/providers/ibm_cloud/cloud_tools/vpc.rb:47:in `block (2 levels) in each_resource'
/Users/nasarkhan/Documents/manageiq/plugins/manageiq-providers-ibm_cloud/lib/manageiq/providers/ibm_cloud/cloud_tools/vpc.rb:47:in `each'
/Users/nasarkhan/Documents/manageiq/plugins/manageiq-providers-ibm_cloud/lib/manageiq/providers/ibm_cloud/cloud_tools/vpc.rb:47:in `block in each_resource'
/Users/nasarkhan/Documents/manageiq/plugins/manageiq-providers-ibm_cloud/lib/manageiq/providers/ibm_cloud/cloud_tools/vpc.rb:40:in `loop'
/Users/nasarkhan/Documents/manageiq/plugins/manageiq-providers-ibm_cloud/lib/manageiq/providers/ibm_cloud/cloud_tools/vpc.rb:40:in `each_resource'
/Users/nasarkhan/Documents/manageiq/plugins/manageiq-providers-ibm_cloud/app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb:45:in `each'
/Users/nasarkhan/Documents/manageiq/plugins/manageiq-providers-ibm_cloud/app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb:45:in `instances'
/Users/nasarkhan/Documents/manageiq/plugins/manageiq-providers-ibm_cloud/app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb:19:in `parse'
```

@miq-bot assign @nasark 
@miq-bot add_label bug

**Comment by nasark** [comment]
I've followed up with the VPC team and they've suggested to open a support ticket. I currently do not have permissions to do so on IBM Cloud and so this may take some time for me to get the appropriate permissions

**Comment by nasark** [comment]
VPC team is looking into this, it seems like there are issues on the Dallas (us-south) region. The current workaround at the provider level is to use a different region
